development:
  secret_key_base: THERE WILL ALREADY BE SOME CRAZY STRING HERE. LEAVE IT THERE.
  twilio_account_sid: 'AC6a02f15490023d899838b3c04bee90b6'
  twilio_auth_token: '810414b8ecb9eb7dc5bc6001cd39f71f'
  twilio_phone_number: '19_167_133_582'


